import { normalizeSelection } from './selection';
import { isOverriddenCommentRule, workingPreferenceRules } from './working-preferences';
import {
  COMMAND_KEYS,
  type Bullet,
  type CommandKey,
  type FragmentBody,
  type FragmentLibrary,
  type Selection,
  type TechFragment,
} from './types';

export const LONG_FILE_LINES = 200;

const COMMAND_LABELS: Record<CommandKey, string> = {
  install: 'Install',
  build: 'Build',
  test: 'Test',
  lint: 'Lint',
  format: 'Format',
  run: 'Run',
};

const PLACEHOLDER_COMMANDS: ReadonlySet<CommandKey> = new Set(['install', 'build', 'test', 'lint']);

const BOUNDARY_SECTIONS = [
  ['always', 'Always'],
  ['ask-first', 'Ask first'],
  ['never', 'Never'],
] as const;

export function compose(selection: Selection, library: FragmentLibrary, date: string): string {
  const sel = normalizeSelection(selection, library);
  const context = library.contexts.find((c) => c.id === sel.context);
  const focusAreas = library.focusAreas.filter((area) => sel.focusAreas.includes(area.id));
  const tech = library.tech.filter((t) => sel.stack.includes(t.id));
  const pick = (bullets: Bullet[], seen: Set<string>) =>
    pickBullets(
      bullets.filter((b) => !isOverriddenCommentRule(b.text, sel.preferences)),
      sel.context,
      seen,
    );

  const out: string[] = [
    '# AGENTS.md',
    '',
    `<!-- Generated by agentsprofiles.com on ${date}. Edit to fit your repo. -->`,
    '',
    '## Project context',
    '',
    context?.summary ?? '<select a project context>',
    '',
    '## Commands',
    '',
    ...commandLines(tech),
    '',
    '## Working rules',
    '',
    ...asList(pick([...library.base.rules, ...(context?.body.rules ?? [])], new Set())),
    '',
  ];

  const areaSections: string[] = [];
  for (const area of focusAreas) {
    const items = pick(area.body.rules, new Set());
    const boundaries: string[] = [];
    for (const [key, label] of BOUNDARY_SECTIONS) {
      const rules = pick(area.body[key], new Set());
      if (rules.length) boundaries.push(`#### ${label}`, '', ...asList(rules), '');
    }
    if (items.length || boundaries.length) {
      areaSections.push(`### ${area.label}`, '', area.scope, '', ...asList(items));
      if (items.length) areaSections.push('');
      areaSections.push(...boundaries);
    }
  }
  if (areaSections.length) out.push('## Area-specific guidance', '', ...areaSections);

  out.push('## Stack guidelines', '');
  if (!tech.length) out.push('<select at least one technology>', '');
  const techSeen = new Set<string>();
  for (const item of tech) {
    const items = pick(item.body.rules, techSeen);
    if (items.length) out.push(`### ${item.label}`, '', ...asList(items), '');
  }

  const customInstructions = sel.customInstructions?.replace(/\r\n?/g, '\n').trim();
  if (customInstructions) out.push('## Project-specific instructions', '', customInstructions, '');

  const preferenceRules = workingPreferenceRules(sel.preferences);
  if (preferenceRules.length)
    out.push('## Working preferences', '', ...asList(preferenceRules), '');

  const bodies: FragmentBody[] = [
    library.base,
    ...(context ? [context.body] : []),
    ...tech.map((t) => t.body),
  ];
  const boundaries: string[] = [];
  for (const [key, label] of BOUNDARY_SECTIONS) {
    const items = pick(
      bodies.flatMap((b) => b[key]),
      new Set(),
    );
    if (items.length) boundaries.push(`### ${label}`, '', ...asList(items), '');
  }
  if (boundaries.length) out.push('## Boundaries', '', ...boundaries);

  return `${out.join('\n').trimEnd()}\n`;
}

export function countLines(markdown: string): number {
  if (markdown === '') return 0;
  return markdown.replace(/\n$/, '').split('\n').length;
}

export function formatLocalDate(date: Date): string {
  const pad = (n: number) => String(n).padStart(2, '0');
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`;
}

function commandLines(tech: TechFragment[]): string[] {
  const lines: string[] = [];
  for (const key of COMMAND_KEYS) {
    const label = COMMAND_LABELS[key];
    const values = tech.flatMap((t) => {
      const command = t.commands[key];
      return command ? [{ tech: t.label, command }] : [];
    });
    if (values.length === 1) {
      lines.push(`- ${label}: \`${values[0].command}\``);
    } else if (values.length > 1) {
      for (const v of values) lines.push(`- ${label} (${v.tech}): \`${v.command}\``);
    } else if (PLACEHOLDER_COMMANDS.has(key)) {
      lines.push(`- ${label}: \`<${key} command>\``);
    }
  }
  return lines;
}

// `seen` is shared across one output section, so duplicates are removed within that section only.
function pickBullets(bullets: Bullet[], contextId: string | null, seen: Set<string>): string[] {
  const result: string[] = [];
  for (const bullet of bullets) {
    if (!applies(bullet, contextId)) continue;
    const text = bullet.text.trim().replace(/\s+/g, ' ');
    if (seen.has(text)) continue;
    seen.add(text);
    result.push(text);
  }
  return result;
}

function applies(bullet: Bullet, contextId: string | null): boolean {
  if (bullet.only.length) return contextId !== null && bullet.only.includes(contextId);
  if (bullet.not.length) return contextId === null || !bullet.not.includes(contextId);
  return true;
}

function asList(items: string[]): string[] {
  return items.map((item) => `- ${item}`);
}
